### ISSUE TITLE
toplogySpreadConstraint selects AZs from an incorrect region.

### ISSUE THREAD

**Issue by nickolanick** [aws/karpenter#3735]
### Version

__Karpenter Version:__ v0.27.0

__Kubernetes Version:__ v1.24.0

### Expected Behavior

We have a deployment with `topologySpreadConstraints`. The deployment is running an EKS cluster in `eu-west-1` region. 
The expected behavior is for pods to spread across all AZs in the `eu-west-1 `region.
```
topologySpreadConstraints:
  - labelSelector:
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
```

### Actual Behavior

Some of the pods are stuck in a pending state, in the karpenter event, I noticed that karpenter tries to schedule the pod on the node that is running in `us-east-1a`, and because the cluster is deployed in `eu-west-1` region, there are no `us-east-1x` AZs available.
```
Warning  FailedScheduling  55m (x8 over 55m)  karpenter          (combined from similar events): Failed to schedule pod, 
incompatible with provisioner "default", no instance type satisfied resources 
{"cpu":"3100m","memory":"4319304Ki","pods":"1"} and requirements karpenter.k8s.aws/instance-size In [12xlarge 2xlarge 
4xlarge 8xlarge large and 2 others], topology.kubernetes.io/zone In [us-east-1a], kubernetes.io/os In [linux]
```

### Steps to Reproduce the Problem

I was able to reproduce the issue, but only in `eu-west-1` region; the same deployment works in `us-east-1`.
I have also verified that all nodes in the cluster are in `eu-west-1`
<img width="849" alt="Screenshot 2023-04-12 at 12 56 33" src="https://user-images.githubusercontent.com/31736783/231437547-098d786a-9aca-4857-9a34-959c0ef9d419.png">

Here is a full deployment spec that I used to reproduce the issue.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-test
  namespace: devops
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: topology-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topology-test
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: tmp
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - tmp
      containers:
      - name: app
        command: ["sleep"]
        args: [ "10000" ]
        image: busybox:latest
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: topology-test
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: topology-test
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
```
AWSNodeTemplate and Provisioner
```
# Source: karpenter-provisioners/templates/tmp-provisioner.yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: tmp
spec:
  subnetSelector:
    aws-ids: "subnet-0eadc682250f4a7e7,subnet-0e172be0e12ea345f,subnet-0fca6ed4430619a37"
  securityGroupSelector:
    Name: k8s.nodes.eks
---
# Source: karpenter-provisioners/templates/tmp-provisioner.yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: tmp
spec:
  labels:
    dedicated: tmp
  taints:
    - key: dedicated
      effect: NoSchedule
      value: tmp
  providerRef:
     name: tmp
```

As a result

3/5 pods are running, the two remaining one complain about us-east-1 AZ
```
topology-test-768fc9fdc7-5mrdt                      1/1     Running             0          106s
topology-test-768fc9fdc7-8g4xc                      1/1     Running   0          106s
topology-test-768fc9fdc7-hnzhq                      0/1     Pending             0          106s
topology-test-768fc9fdc7-rw8n6                      1/1     Running             0          106s
topology-test-768fc9fdc7-skcq7                       0/1     Pending             0          106s
```

Here is the log message, which is the same as the original one.
```
  Warning  FailedScheduling  95s (x15 over 2m35s)  karpenter          (combined from similar events): Failed to schedule pod,
   incompatible with provisioner "tmp", no instance type 
   satisfied resources {"pods":"1"} and requirements karpenter.sh/provisioner-name In [tmp], kubernetes.io/os In [linux], 
   karpenter.sh/capacity-type In [on-demand], karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-
   generation Exists >2, dedicated In [tmp], kubernetes.io/arch In [amd64], topology.kubernetes.io/zone In [us-east-1a]
```
As you can see, once again, the pod has a requirement to get deployed into `us-east-1a` zone  `topology.kubernetes.io/zone In [us-east-1a]`, which is not expected behavior. 

### Resource Specs and Logs

Provisioner
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  labels:
    argocd.argoproj.io/instance: karpenter-provisioners-eu-west-1
  name: default
spec:
  consolidation:
    enabled: true
  labels:
    dedicated: k8s.nodes
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - small
    - large
    - xlarge
    - 2xlarge
    - 4xlarge
    - 8xlarge
    - 12xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  ttlSecondsUntilExpired: 2592000
```

Karpenter logs
```
2023-04-11T09:04:02.514Z        ERROR   controller.provisioner  Could not schedule pod, incompatible with provisioner "dmz", did not tolerate dedicated=dmz:NoSchedule; incompatible with provisioner "on-demand", did not tolerate dedicated=on-demand:NoSchedule; incompatible with provisioner "default", no instance type satisfied resources {"cpu":"3100m","memory":"4319304Ki","pods":"1"} and requirements kubernetes.io/os In [linux], karpenter.sh/provisioner-name In [default], karpenter.k8s.aws/instance-size In [12xlarge 2xlarge 4xlarge 8xlarge large and 2 others], dedicated In [k8s.nodes], karpenter.sh/capacity-type In [on-demand spot], karpenter.k8s.aws/instance-category In [c m r], kubernetes.io/arch In [amd64], topology.kubernetes.io/zone In [us-east-1c]   {"commit": "dc3af1a", "pod": "<pod-ns>/<pod-name>""}
2023-04-11T09:04:02.515Z        ERROR   controller.provisioner  Could not schedule pod, incompatible with provisioner "dmz", did not tolerate dedicated=dmz:NoSchedule; incompatible with provisioner "on-demand", did not tolerate dedicated=on-demand:NoSchedule; incompatible with provisioner "default", no instance type satisfied resources {"cpu":"3100m","memory":"4319304Ki","pods":"1"} and requirements karpenter.sh/provisioner-name In [default], karpenter.k8s.aws/instance-category In [c m r], topology.kubernetes.io/zone In [us-east-1a], karpenter.sh/capacity-type In [on-demand spot], karpenter.k8s.aws/instance-size In [12xlarge 2xlarge 4xlarge 8xlarge large and 2 others], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], dedicated In [k8s.nodes]   {"commit": "dc3af1a", "pod": "<pod-ns>/<pod-name>"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nickolanick** [comment]
I have a theory; please let me know if it sounds reasonable :) 

If I understand correctly, the azs are discovered based on the subnetSelector on AWSNodeTemplate.
```
  subnetSelector:
    Name: private-eks-*.k8s
```
I have checked the status of it and looks like it only discovered subnets from eu-west-1
```
status:
  securityGroups:
  - id: sg-04b314fdf38c74b15
  subnets:
  - id: subnet-0a2fd30f5b0593f19
    zone: eu-west-1a
  - id: subnet-025dc87f05d0b3c07
    zone: eu-west-1b
  - id: subnet-081bbbcd61c17f96a
    zone: eu-west-1c
```
But, in `us-east-1 `we have subnets with the same name in a different vpc. Is it possible that for AZ discovery, karpenter discovered subnets from both regions and used the according AZs associated with those subnets?

If so, this sounds like a bug, as I would expect karpenter only to select subnets within the cluster region ( `eu-west-1` ).

**Comment by nickolanick** [comment]
I have changed the subnet selector and manually populated it with only subnets in one region. Same results.
I have also verified that all nodes in the cluster are in `eu-west-1`
<img width="849" alt="Screenshot 2023-04-12 at 12 56 33" src="https://user-images.githubusercontent.com/31736783/231437547-098d786a-9aca-4857-9a34-959c0ef9d419.png">

I was able to reproduce the issue, but only in `eu-west-1` region; the same deployment works in `us-east-1`
Here is a full deployment spec that I used to reproduce the issue.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-test
  namespace: devops
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: topology-test
      app.kubernetes.io/name: topology-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: topology-test
        app.kubernetes.io/name: topology-test
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: tmp
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions: # OR
                - key: "karpenter.sh/capacity-type" # AND
                  operator: "In"
                  values: ["on-demand"]
                - key: dedicated
                  operator: In
                  values:
                  - tmp
      containers:
      - name: app
        command: ["sleep"]
        args: [ "10000" ]
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 7G
          requests:
            cpu: "7"
            memory: 7G
      terminationGracePeriodSeconds: 300
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: topology-test
            app.kubernetes.io/name: topology-test
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: topology-test
            app.kubernetes.io/name: topology-test
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
```
AWSNodeTemplate and Provisioner
```
---
# Source: karpenter-provisioners/templates/tmp-provisioner.yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: tmp
  annotations:
    avp.kubernetes.io/secret-version: "2"
spec:
  subnetSelector:
    aws-ids: "subnet-0eadc682250f4a7e7,subnet-0e172be0e12ea345f,subnet-0fca6ed4430619a37"
  securityGroupSelector:
    Name: k8s.nodes.eks
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 50Gi
        iops: 3000
        throughput: 125
        deleteOnTermination: true
        encrypted: true
---
# Source: karpenter-provisioners/templates/tmp-provisioner.yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: tmp
spec:
  consolidation:
    enabled: false
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"] # Prefer spot.
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r"]
    - key: "karpenter.k8s.aws/instance-size"
      operator: In
      values: ["small", "large", "xlarge", "2xlarge","4xlarge","8xlarge","12xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "kubernetes.io/os"
      operator: In
      values:
        - "linux"
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["1"]
    - key: "karpenter.k8s.aws/instance-memory"
      operator: Gt
      values: ["512"]
  labels:
    dedicated: tmp
  taints:
    - key: dedicated
      effect: NoSchedule
      value: tmp
  providerRef:
     name: tmp
  ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;
```

**Comment by nickolanick** [comment]
> Can you look for a "discovered offerings" log line in your Karpenter logs and see what it says? e.g.
> 
> ```
> karpenter-77c4d8c74c-z9ww7 controller 2023-04-12T13:05:33.287Z	DEBUG	controller.node	discovered offerings for instance types	{"commit": "4540741", "node": "ip-192-168-151-79.us-west-2.compute.internal", "zones": ["us-west-2a", "us-west-2c", "us-west-2d"], "instance-type-count": 628, "node-template": "default"}
> ```


Logs don't contain "discovered offerings", I have checked "discovered" and "offerings" separately. 
<img width="1716" alt="Screenshot 2023-04-12 at 15 31 43" src="https://user-images.githubusercontent.com/31736783/231473807-b5f23c04-2547-4e8f-9547-868e1637b601.png">
<img width="1704" alt="Screenshot 2023-04-12 at 15 31 01" src="https://user-images.githubusercontent.com/31736783/231473867-6285e22d-9bf1-4adc-8eba-93d0f942b951.png">

**Comment by tzneal** [comment]
Try restarting the karpenter deployment, its not displayed often.

**Comment by nickolanick** [comment]
> tzneal
The screenshot I shared is right after restart, ~1 minute after.

**Comment by nickolanick** [comment]
I just checked the source code I believe you are referring to the new log format output, which was added five days ago [here](https://github.com/aws/karpenter/commit/550ca8714f0c6db70fbd063d58c1e48dc9e82e31). We don'r run this version yet. (0.27.0 right now)
<img width="1091" alt="Screenshot 2023-04-12 at 16 03 59" src="https://user-images.githubusercontent.com/31736783/231482688-d9ac6961-9c6c-4ac8-bf67-7e9ddb7a0cfd.png">
Before the change, the log looked like this "discovered EC2 instance types zonal offerings"; I filtered for it.


<img width="1724" alt="Screenshot 2023-04-12 at 16 06 21" src="https://user-images.githubusercontent.com/31736783/231483225-4865d741-45e8-4429-a559-2c6e2a3cc64e.png">

**Comment by tzneal** [comment]
Ah, sorry, yeah I didn't check to see if the error message changed.  Do you have multiple node templates? It still looks like there is one discovering by the subnet name per the last log line you posted.

**Comment by tzneal** [comment]
The valid zones for topology spread are all of those discovered by any node template that Karpenter can see.  Restricting a single provisioner/node-template won't solve the issue you are seeing. You'll need to make sure that none of them discover a subnet in another region.

In your other cluster you may be selecting them differently, we would need the full set of all provisioners/node templates from both clusters to inspect.  

Changing your other node template to specify the correct subnets by ID should solve this.

**Comment by nickolanick** [comment]
I have modified all of subnetSelectors to have the region in selector value, so it can't resolve the subnet from another region.
```
➜  tmp k get awsnodetemplate -o yaml | grep -A 1 "subnetSelector:"
    subnetSelector:
      Name: private-eks-*.k8s.eu-west-1.*.firebolt.io
--
    subnetSelector:
      Name: dmz-*.k8s.eu-west-1.*.firebolt.io
--
    subnetSelector:
      Name: private-eks-*.k8s.eu-west-1.*.firebolt.io
--
    subnetSelector:
      Name: private-eks-*.k8s.eu-west-1.*.firebolt.io
```
I have also restarted the karpenter pod, but the issue persists. ( BTW the same behaviour is across multiple environments )

**Comment by nickolanick** [comment]
Also, the describeSubnets is regionally scoped; shouldn't it discover only in the region that karpenter is deployed in ?

**Comment by nickolanick** [comment]
That's exactly what happened; one of our provisions had this requirement across all regions.
```
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-east-1a
    - us-east-1b
    - us-east-1c
```
After changing it corresponds to the appropriate region everything started working. 
Thanks once again!

But it's a bit confusing that misconfiguration in one provisioner impacted all other provisions in the cluster.

**Comment by billrayburn** [comment]
Keeping open to track that we could add config validation.

**Comment by ellistarn** [comment]
Kubernetes validation best practices recommend against cross-resource validation. This is to remove ordering requirements, where object A would need to be applied before object B, which significantly complicates configuration. For this reason, I don't think we want to validate anything. Further, I don't think we want to log when we detect this, since it's a viable use case that some customers *are* using. 

One option is to simply not define zonal requirements, and Karpenter will use whatever you have available from the subnets you've configured. 

Feel free to reopen if you want to continue discussion
